# Generated by Django 4.0.4 on 2022-05-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='update_time',
        ),
    ]
